=== Cephou/XMLFormation/schema/dtd-exercise.dtd
<!-- Racine -->
<!ELEMENT repertoire (contact*)>

<!-- Personne -->
<!ELEMENT contact (firstname, lastname, address, emails, phones)>
<!ATTLIST contact sex (male | female) #REQUIRED>

<!-- lastname et firstname -->
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>

<!-- Bloc adresse -->
<!ELEMENT address (number, street, postcode, city)>

<!ELEMENT number (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT city (#PCDATA)>

<!-- Bloc phone -->
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>

<!-- Bloc email -->
<!ELEMENT emails (email+)>
<!ELEMENT email (#PCDATA)>

=== Cephou/XMLFormation/xml/dtd-exercise.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE repertoire SYSTEM "../schema/dtd-exercise.dtd">


<repertoire>

      <contact sex="male">
        <firstname>Stan</firstname>
        <lastname>Marsh</lastname>
        <address>
            <number>7</number>
            <street>impasse du chemin</street>
            <postcode>75000</postcode>
            <city>Paris</city>
        </address>
        <emails>
          <email>stan.marsh@etu.univ-southpark.com</email>
          <email>stan.marsh@gmail.com</email>
        </emails>
        <phones>
          <phone type="fixe">2564-256</phone>
        </phones>
      </contact>

      <contact sex="male">
        <firstname>Eric</firstname>
        <lastname>Cartman</lastname>
        <address>
            <number>28</number>
            <street>avenue de la rÃ©publique</street>
            <postcode>86000</postcode>
            <city>Poitiers</city>
        </address>
        <emails>
          <email>eric.cartman@gmail.com</email>
        </emails>
        <phones>
          <phone type="portable">464-256</phone>
        </phones>
      </contact>

</repertoire>
