=== Cephou/XMLFormation/schema/schema-exercise.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Elément racine -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <!-- Rappels de syntaxe

    Elements simple : <xsd:element name="nom_de_l'élément_simple" type="xsd:type_de_l'élément_simple" />
    Element

  -->

  <!-- lE CODE CI DESSOUS DEVRA ÊTRE RETIRE POUR L'EXERCICE -->

  <!-- Balise Email -->
  <xsd:element name="email">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="type">
            <xsd:simpleType>
              <xsd:restriction base="xsd:string">
                <xsd:enumeration value="perso"/>
                <xsd:enumeration value="pro"/>
              </xsd:restriction>
            </xsd:simpleType>
          </xsd:attribute>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <!-- Balise Emails -->
  <xsd:element name="emails">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="email" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="firstname" type="xsd:string"></xsd:element>
  <xsd:element name="name" type="xsd:string"></xsd:element>

  <!-- Balise contact -->
  <xsd:element name="contact">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="firstname"/>
        <xsd:element ref="name"/>
        <xsd:element ref="emails"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- Balise repertoire -->
  <xsd:element name="repertoire">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="contact" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== Cephou/XMLFormation/xml/schema-exercise.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<repertoire xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema-exercise.xsd">

  <contact>
    <firstname>Stan</firstname>
    <lastname>Marsh</lastname>
    <emails>
      <email type="pro">stan.marsh@etu.univ-southpark.com</email>
      <email type="perso">stan.marsh@gmail.com</email>
    </emails>
  </contact>
  <contact>
    <firstname>Kenny</firstname>
    <lastname>McCormick</lastname>
    <emails>
      <email type="pro">kenny.mccormick@gmail.com</email>
      <email type="perso">kenny.mccormick@gmail.com</email>
    </emails>
  </contact>

</repertoire>
